package com.foodsite.food.dao;

import com.foodsite.food.entity.Buyfood;
import com.foodsite.food.entity.BuyfoodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyfoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    long countByExample(BuyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int deleteByExample(BuyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int insert(Buyfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int insertSelective(Buyfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    List<Buyfood> selectByExampleWithBLOBs(BuyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    List<Buyfood> selectByExample(BuyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    Buyfood selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Buyfood record, @Param("example") BuyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Buyfood record, @Param("example") BuyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Buyfood record, @Param("example") BuyfoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Buyfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Buyfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyfood
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Buyfood record);
}