package com.android.app.entity;

import java.io.Serializable;
import java.util.Date;

public class EstimateTable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_table.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_table.es_id
     *
     * @mbg.generated
     */
    private Long esId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_table.es_text
     *
     * @mbg.generated
     */
    private String esText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_table.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_table.dy_id
     *
     * @mbg.generated
     */
    private Integer dyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_table.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_table.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_table.id
     *
     * @return the value of estimate_table.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_table.id
     *
     * @param id the value for estimate_table.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_table.es_id
     *
     * @return the value of estimate_table.es_id
     *
     * @mbg.generated
     */
    public Long getEsId() {
        return esId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_table.es_id
     *
     * @param esId the value for estimate_table.es_id
     *
     * @mbg.generated
     */
    public void setEsId(Long esId) {
        this.esId = esId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_table.es_text
     *
     * @return the value of estimate_table.es_text
     *
     * @mbg.generated
     */
    public String getEsText() {
        return esText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_table.es_text
     *
     * @param esText the value for estimate_table.es_text
     *
     * @mbg.generated
     */
    public void setEsText(String esText) {
        this.esText = esText == null ? null : esText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_table.u_id
     *
     * @return the value of estimate_table.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_table.u_id
     *
     * @param uId the value for estimate_table.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_table.dy_id
     *
     * @return the value of estimate_table.dy_id
     *
     * @mbg.generated
     */
    public Integer getDyId() {
        return dyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_table.dy_id
     *
     * @param dyId the value for estimate_table.dy_id
     *
     * @mbg.generated
     */
    public void setDyId(Integer dyId) {
        this.dyId = dyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_table.gmt_create
     *
     * @return the value of estimate_table.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_table.gmt_create
     *
     * @param gmtCreate the value for estimate_table.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_table.gmt_update
     *
     * @return the value of estimate_table.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_table.gmt_update
     *
     * @param gmtUpdate the value for estimate_table.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}