package com.foodsite.food.entity;

import java.io.Serializable;
import java.util.Date;

public class Admin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ad_id
     *
     * @mbg.generated
     */
    private Long adId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.amd_name
     *
     * @mbg.generated
     */
    private String amdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.amd_password
     *
     * @mbg.generated
     */
    private String amdPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ad_id
     *
     * @return the value of admin.ad_id
     *
     * @mbg.generated
     */
    public Long getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ad_id
     *
     * @param adId the value for admin.ad_id
     *
     * @mbg.generated
     */
    public void setAdId(Long adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.amd_name
     *
     * @return the value of admin.amd_name
     *
     * @mbg.generated
     */
    public String getAmdName() {
        return amdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.amd_name
     *
     * @param amdName the value for admin.amd_name
     *
     * @mbg.generated
     */
    public void setAmdName(String amdName) {
        this.amdName = amdName == null ? null : amdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.amd_password
     *
     * @return the value of admin.amd_password
     *
     * @mbg.generated
     */
    public String getAmdPassword() {
        return amdPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.amd_password
     *
     * @param amdPassword the value for admin.amd_password
     *
     * @mbg.generated
     */
    public void setAmdPassword(String amdPassword) {
        this.amdPassword = amdPassword == null ? null : amdPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.gmt_create
     *
     * @return the value of admin.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.gmt_create
     *
     * @param gmtCreate the value for admin.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.gmt_update
     *
     * @return the value of admin.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.gmt_update
     *
     * @param gmtUpdate the value for admin.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}