package com.foodsite.food.entity;

import java.io.Serializable;
import java.util.Date;

public class Buyfood implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.bf_id
     *
     * @mbg.generated
     */
    private Long bfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.f_name
     *
     * @mbg.generated
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.f_photo
     *
     * @mbg.generated
     */
    private String fPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.unit_price
     *
     * @mbg.generated
     */
    private Integer unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.food_type
     *
     * @mbg.generated
     */
    private String foodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyfood.f_desc
     *
     * @mbg.generated
     */
    private String fDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.id
     *
     * @return the value of buyfood.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.id
     *
     * @param id the value for buyfood.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.bf_id
     *
     * @return the value of buyfood.bf_id
     * @mbg.generated
     */
    public Long getBfId() {
        return bfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.bf_id
     *
     * @param bfId the value for buyfood.bf_id
     * @mbg.generated
     */
    public void setBfId(Long bfId) {
        this.bfId = bfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.f_name
     *
     * @return the value of buyfood.f_name
     * @mbg.generated
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.f_name
     *
     * @param fName the value for buyfood.f_name
     * @mbg.generated
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.f_photo
     *
     * @return the value of buyfood.f_photo
     * @mbg.generated
     */
    public String getfPhoto() {
        return fPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.f_photo
     *
     * @param fPhoto the value for buyfood.f_photo
     * @mbg.generated
     */
    public void setfPhoto(String fPhoto) {
        this.fPhoto = fPhoto == null ? null : fPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.unit_price
     *
     * @return the value of buyfood.unit_price
     * @mbg.generated
     */
    public Integer getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.unit_price
     *
     * @param unitPrice the value for buyfood.unit_price
     * @mbg.generated
     */
    public void setUnitPrice(Integer unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.u_id
     *
     * @return the value of buyfood.u_id
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.u_id
     *
     * @param uId the value for buyfood.u_id
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.food_type
     *
     * @return the value of buyfood.food_type
     * @mbg.generated
     */
    public String getFoodType() {
        return foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.food_type
     *
     * @param foodType the value for buyfood.food_type
     * @mbg.generated
     */
    public void setFoodType(String foodType) {
        this.foodType = foodType == null ? null : foodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.gmt_create
     *
     * @return the value of buyfood.gmt_create
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.gmt_create
     *
     * @param gmtCreate the value for buyfood.gmt_create
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.gmt_update
     *
     * @return the value of buyfood.gmt_update
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.gmt_update
     *
     * @param gmtUpdate the value for buyfood.gmt_update
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyfood.f_desc
     *
     * @return the value of buyfood.f_desc
     * @mbg.generated
     */
    public String getfDesc() {
        return fDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyfood.f_desc
     *
     * @param fDesc the value for buyfood.f_desc
     * @mbg.generated
     */
    public void setfDesc(String fDesc) {
        this.fDesc = fDesc == null ? null : fDesc.trim();
    }
}