package com.foodsite.food.entity;

import java.io.Serializable;
import java.util.Date;

public class DiscussFood implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_food.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_food.df_id
     *
     * @mbg.generated
     */
    private Long dfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_food.f_name
     *
     * @mbg.generated
     */
    private String fName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_food.f_foot
     *
     * @mbg.generated
     */
    private String fFoot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_food.f_user
     *
     * @mbg.generated
     */
    private Integer fUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_food.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_food.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_food.f_desc
     *
     * @mbg.generated
     */
    private String fDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_food.id
     *
     * @return the value of discuss_food.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_food.id
     *
     * @param id the value for discuss_food.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_food.df_id
     *
     * @return the value of discuss_food.df_id
     *
     * @mbg.generated
     */
    public Long getDfId() {
        return dfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_food.df_id
     *
     * @param dfId the value for discuss_food.df_id
     *
     * @mbg.generated
     */
    public void setDfId(Long dfId) {
        this.dfId = dfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_food.f_name
     *
     * @return the value of discuss_food.f_name
     *
     * @mbg.generated
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_food.f_name
     *
     * @param fName the value for discuss_food.f_name
     *
     * @mbg.generated
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_food.f_foot
     *
     * @return the value of discuss_food.f_foot
     *
     * @mbg.generated
     */
    public String getfFoot() {
        return fFoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_food.f_foot
     *
     * @param fFoot the value for discuss_food.f_foot
     *
     * @mbg.generated
     */
    public void setfFoot(String fFoot) {
        this.fFoot = fFoot == null ? null : fFoot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_food.f_user
     *
     * @return the value of discuss_food.f_user
     *
     * @mbg.generated
     */
    public Integer getfUser() {
        return fUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_food.f_user
     *
     * @param fUser the value for discuss_food.f_user
     *
     * @mbg.generated
     */
    public void setfUser(Integer fUser) {
        this.fUser = fUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_food.gmt_create
     *
     * @return the value of discuss_food.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_food.gmt_create
     *
     * @param gmtCreate the value for discuss_food.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_food.gmt_update
     *
     * @return the value of discuss_food.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_food.gmt_update
     *
     * @param gmtUpdate the value for discuss_food.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_food.f_desc
     *
     * @return the value of discuss_food.f_desc
     *
     * @mbg.generated
     */
    public String getfDesc() {
        return fDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_food.f_desc
     *
     * @param fDesc the value for discuss_food.f_desc
     *
     * @mbg.generated
     */
    public void setfDesc(String fDesc) {
        this.fDesc = fDesc == null ? null : fDesc.trim();
    }
}