package com.foodsite.food.entity;

import java.io.Serializable;
import java.util.Date;

public class FoodUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_user.fu_id
     *
     * @mbg.generated
     */
    private Long fuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_user.user_pass
     *
     * @mbg.generated
     */
    private String userPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_user.permission
     *
     * @mbg.generated
     */
    private Integer permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_user.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_user.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_user.id
     *
     * @return the value of food_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_user.id
     *
     * @param id the value for food_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_user.fu_id
     *
     * @return the value of food_user.fu_id
     *
     * @mbg.generated
     */
    public Long getFuId() {
        return fuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_user.fu_id
     *
     * @param fuId the value for food_user.fu_id
     *
     * @mbg.generated
     */
    public void setFuId(Long fuId) {
        this.fuId = fuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_user.nick_name
     *
     * @return the value of food_user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_user.nick_name
     *
     * @param nickName the value for food_user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_user.user_name
     *
     * @return the value of food_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_user.user_name
     *
     * @param userName the value for food_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_user.user_pass
     *
     * @return the value of food_user.user_pass
     *
     * @mbg.generated
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_user.user_pass
     *
     * @param userPass the value for food_user.user_pass
     *
     * @mbg.generated
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass == null ? null : userPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_user.permission
     *
     * @return the value of food_user.permission
     *
     * @mbg.generated
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_user.permission
     *
     * @param permission the value for food_user.permission
     *
     * @mbg.generated
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_user.gmt_create
     *
     * @return the value of food_user.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_user.gmt_create
     *
     * @param gmtCreate the value for food_user.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_user.gmt_update
     *
     * @return the value of food_user.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_user.gmt_update
     *
     * @param gmtUpdate the value for food_user.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}