package com.foodsite.food.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

@JsonFormat(pattern = "YYYYddMM")
public class LiuyanTable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan_table.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan_table.liuyan_id
     *
     * @mbg.generated
     */
    private Long liuyanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan_table.liuyan_user
     *
     * @mbg.generated
     */
    private Integer liuyanUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan_table.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan_table.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan_table.liuyan_text
     *
     * @mbg.generated
     */
    private String liuyanText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan_table.id
     *
     * @return the value of liuyan_table.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan_table.id
     *
     * @param id the value for liuyan_table.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan_table.liuyan_id
     *
     * @return the value of liuyan_table.liuyan_id
     *
     * @mbg.generated
     */
    public Long getLiuyanId() {
        return liuyanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan_table.liuyan_id
     *
     * @param liuyanId the value for liuyan_table.liuyan_id
     *
     * @mbg.generated
     */
    public void setLiuyanId(Long liuyanId) {
        this.liuyanId = liuyanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan_table.liuyan_user
     *
     * @return the value of liuyan_table.liuyan_user
     *
     * @mbg.generated
     */
    public Integer getLiuyanUser() {
        return liuyanUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan_table.liuyan_user
     *
     * @param liuyanUser the value for liuyan_table.liuyan_user
     *
     * @mbg.generated
     */
    public void setLiuyanUser(Integer liuyanUser) {
        this.liuyanUser = liuyanUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan_table.gmt_create
     *
     * @return the value of liuyan_table.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan_table.gmt_create
     *
     * @param gmtCreate the value for liuyan_table.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan_table.gmt_update
     *
     * @return the value of liuyan_table.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan_table.gmt_update
     *
     * @param gmtUpdate the value for liuyan_table.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan_table.liuyan_text
     *
     * @return the value of liuyan_table.liuyan_text
     *
     * @mbg.generated
     */
    public String getLiuyanText() {
        return liuyanText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan_table.liuyan_text
     *
     * @param liuyanText the value for liuyan_table.liuyan_text
     *
     * @mbg.generated
     */
    public void setLiuyanText(String liuyanText) {
        this.liuyanText = liuyanText == null ? null : liuyanText.trim();
    }
}