package com.foodsite.food.entity;

import java.io.Serializable;
import java.util.Date;

public class TuijianFood implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian_food.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian_food.tui_id
     *
     * @mbg.generated
     */
    private Long tuiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian_food.food_name
     *
     * @mbg.generated
     */
    private String foodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian_food.food_photo
     *
     * @mbg.generated
     */
    private String foodPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian_food.food_uid
     *
     * @mbg.generated
     */
    private Integer foodUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian_food.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian_food.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuijian_food.food_desc
     *
     * @mbg.generated
     */
    private String foodDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian_food.id
     *
     * @return the value of tuijian_food.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian_food.id
     *
     * @param id the value for tuijian_food.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian_food.tui_id
     *
     * @return the value of tuijian_food.tui_id
     *
     * @mbg.generated
     */
    public Long getTuiId() {
        return tuiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian_food.tui_id
     *
     * @param tuiId the value for tuijian_food.tui_id
     *
     * @mbg.generated
     */
    public void setTuiId(Long tuiId) {
        this.tuiId = tuiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian_food.food_name
     *
     * @return the value of tuijian_food.food_name
     *
     * @mbg.generated
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian_food.food_name
     *
     * @param foodName the value for tuijian_food.food_name
     *
     * @mbg.generated
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian_food.food_photo
     *
     * @return the value of tuijian_food.food_photo
     *
     * @mbg.generated
     */
    public String getFoodPhoto() {
        return foodPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian_food.food_photo
     *
     * @param foodPhoto the value for tuijian_food.food_photo
     *
     * @mbg.generated
     */
    public void setFoodPhoto(String foodPhoto) {
        this.foodPhoto = foodPhoto == null ? null : foodPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian_food.food_uid
     *
     * @return the value of tuijian_food.food_uid
     *
     * @mbg.generated
     */
    public Integer getFoodUid() {
        return foodUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian_food.food_uid
     *
     * @param foodUid the value for tuijian_food.food_uid
     *
     * @mbg.generated
     */
    public void setFoodUid(Integer foodUid) {
        this.foodUid = foodUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian_food.gmt_create
     *
     * @return the value of tuijian_food.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian_food.gmt_create
     *
     * @param gmtCreate the value for tuijian_food.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian_food.gmt_update
     *
     * @return the value of tuijian_food.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian_food.gmt_update
     *
     * @param gmtUpdate the value for tuijian_food.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuijian_food.food_desc
     *
     * @return the value of tuijian_food.food_desc
     *
     * @mbg.generated
     */
    public String getFoodDesc() {
        return foodDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuijian_food.food_desc
     *
     * @param foodDesc the value for tuijian_food.food_desc
     *
     * @mbg.generated
     */
    public void setFoodDesc(String foodDesc) {
        this.foodDesc = foodDesc == null ? null : foodDesc.trim();
    }
}