package com.breakpoint.dao;

import com.breakpoint.dto.PageInfo;
import com.breakpoint.entity.TbAlbum;
import com.breakpoint.entity.TbAlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    long countByExample(TbAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    int deleteByExample(TbAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    int insert(TbAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    int insertSelective(TbAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    List<TbAlbum> selectByExample(TbAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    TbAlbum selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbAlbum record, @Param("example") TbAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbAlbum record, @Param("example") TbAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbAlbum record);


    List<TbAlbum> selectByPageListPage(@Param("pageInfo") PageInfo pageInfo);
}