package com.breakpoint.dao;

import com.breakpoint.entity.BlogTopic;
import com.breakpoint.entity.Youhuijuan;
import com.breakpoint.entity.YouhuijuanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YouhuijuanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    long countByExample(YouhuijuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    int deleteByExample(YouhuijuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    int insert(Youhuijuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    int insertSelective(Youhuijuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    List<Youhuijuan> selectByExample(YouhuijuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    Youhuijuan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Youhuijuan record, @Param("example") YouhuijuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Youhuijuan record, @Param("example") YouhuijuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Youhuijuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table youhuijuan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Youhuijuan record);


    /**
     * 优惠卷的查询的操作
     * @param pageStart
     * @param pageSize
     * @param userId
     * @return
     */
    List<Youhuijuan> selectYouhuijuanByPageInfo(@Param("pageStart") int pageStart, @Param("pageSize") int pageSize,
                                          @Param("userId") Long userId,@Param("keyWords") String keyWords);

    int countYouhuijuanByPageInfo(@Param("userId") Long userId,@Param("keyWords") String keyWords);
}