package com.foodsite.food.dao;

import com.foodsite.food.entity.FoodUser;
import com.foodsite.food.entity.FoodUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_user
     *
     * @mbg.generated
     */
    long countByExample(FoodUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_user
     *
     * @mbg.generated
     */
    int deleteByExample(FoodUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_user
     *
     * @mbg.generated
     */
    int insert(FoodUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_user
     *
     * @mbg.generated
     */
    int insertSelective(FoodUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_user
     *
     * @mbg.generated
     */
    List<FoodUser> selectByExample(FoodUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FoodUser record, @Param("example") FoodUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FoodUser record, @Param("example") FoodUserExample example);
}