package com.foodsite.food.dao;

import com.foodsite.food.entity.LiuyanTable;
import com.foodsite.food.entity.LiuyanTableExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface LiuyanTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    long countByExample(LiuyanTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int deleteByExample(LiuyanTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int insert(LiuyanTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int insertSelective(LiuyanTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    List<LiuyanTable> selectByExampleWithBLOBs(LiuyanTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    List<LiuyanTable> selectByExample(LiuyanTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    LiuyanTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LiuyanTable record, @Param("example") LiuyanTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LiuyanTable record, @Param("example") LiuyanTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LiuyanTable record, @Param("example") LiuyanTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LiuyanTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LiuyanTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liuyan_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LiuyanTable record);


    /**
     * 查询留言信息
     *
     * @param liuyanUser
     * @param start
     * @param pageSize
     * @return
     */
    List<LiuyanTable> selectLiuYanListByPage(@Param("liuyanUser") Integer liuyanUser, @Param("start") int start,
                                             @Param("pageSize") int pageSize);

    /**
     * 查询相应的数目
     *
     * @param liuyanUser
     * @return
     */
    int selectLiuYanListByPageCount(@Param("liuyanUser") Integer liuyanUser);


}