package com.android.app.entity;

import java.util.Date;

public class DynamicTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_table.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_table.dy_id
     *
     * @mbg.generated
     */
    private Long dyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_table.dy_title
     *
     * @mbg.generated
     */
    private String dyTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_table.dy_type
     *
     * @mbg.generated
     */
    private Integer dyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_table.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_table.read_count
     *
     * @mbg.generated
     */
    private Integer readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_table.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_table.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_table.dy_text
     *
     * @mbg.generated
     */
    private String dyText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_table.id
     *
     * @return the value of dynamic_table.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_table.id
     *
     * @param id the value for dynamic_table.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_table.dy_id
     *
     * @return the value of dynamic_table.dy_id
     *
     * @mbg.generated
     */
    public Long getDyId() {
        return dyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_table.dy_id
     *
     * @param dyId the value for dynamic_table.dy_id
     *
     * @mbg.generated
     */
    public void setDyId(Long dyId) {
        this.dyId = dyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_table.dy_title
     *
     * @return the value of dynamic_table.dy_title
     *
     * @mbg.generated
     */
    public String getDyTitle() {
        return dyTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_table.dy_title
     *
     * @param dyTitle the value for dynamic_table.dy_title
     *
     * @mbg.generated
     */
    public void setDyTitle(String dyTitle) {
        this.dyTitle = dyTitle == null ? null : dyTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_table.dy_type
     *
     * @return the value of dynamic_table.dy_type
     *
     * @mbg.generated
     */
    public Integer getDyType() {
        return dyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_table.dy_type
     *
     * @param dyType the value for dynamic_table.dy_type
     *
     * @mbg.generated
     */
    public void setDyType(Integer dyType) {
        this.dyType = dyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_table.u_id
     *
     * @return the value of dynamic_table.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_table.u_id
     *
     * @param uId the value for dynamic_table.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_table.read_count
     *
     * @return the value of dynamic_table.read_count
     *
     * @mbg.generated
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_table.read_count
     *
     * @param readCount the value for dynamic_table.read_count
     *
     * @mbg.generated
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_table.gmt_create
     *
     * @return the value of dynamic_table.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_table.gmt_create
     *
     * @param gmtCreate the value for dynamic_table.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_table.gmt_update
     *
     * @return the value of dynamic_table.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_table.gmt_update
     *
     * @param gmtUpdate the value for dynamic_table.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_table.dy_text
     *
     * @return the value of dynamic_table.dy_text
     *
     * @mbg.generated
     */
    public String getDyText() {
        return dyText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_table.dy_text
     *
     * @param dyText the value for dynamic_table.dy_text
     *
     * @mbg.generated
     */
    public void setDyText(String dyText) {
        this.dyText = dyText == null ? null : dyText.trim();
    }
}