package com.breakpoint.entity;

import java.util.Date;

public class Liuyan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.piture_url
     *
     * @mbg.generated
     */
    private String pitureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liuyan.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.id
     *
     * @return the value of liuyan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.id
     *
     * @param id the value for liuyan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.user_name
     *
     * @return the value of liuyan.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.user_name
     *
     * @param userName the value for liuyan.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.message
     *
     * @return the value of liuyan.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.message
     *
     * @param message the value for liuyan.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.type
     *
     * @return the value of liuyan.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.type
     *
     * @param type the value for liuyan.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.piture_url
     *
     * @return the value of liuyan.piture_url
     *
     * @mbg.generated
     */
    public String getPitureUrl() {
        return pitureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.piture_url
     *
     * @param pitureUrl the value for liuyan.piture_url
     *
     * @mbg.generated
     */
    public void setPitureUrl(String pitureUrl) {
        this.pitureUrl = pitureUrl == null ? null : pitureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.gmt_create
     *
     * @return the value of liuyan.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.gmt_create
     *
     * @param gmtCreate the value for liuyan.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liuyan.gmt_update
     *
     * @return the value of liuyan.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liuyan.gmt_update
     *
     * @param gmtUpdate the value for liuyan.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}