package com.android.app.dao;

import com.android.app.entity.DynamicTable;
import com.android.app.entity.DynamicTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DynamicTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    long countByExample(DynamicTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int deleteByExample(DynamicTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int insert(DynamicTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int insertSelective(DynamicTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    List<DynamicTable> selectByExampleWithBLOBs(DynamicTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    List<DynamicTable> selectByExample(DynamicTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    DynamicTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DynamicTable record, @Param("example") DynamicTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DynamicTable record, @Param("example") DynamicTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DynamicTable record, @Param("example") DynamicTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DynamicTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DynamicTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DynamicTable record);
}