package com.android.app.dao;

import com.android.app.entity.EstimateTable;
import com.android.app.entity.EstimateTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EstimateTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    long countByExample(EstimateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    int deleteByExample(EstimateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    int insert(EstimateTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    int insertSelective(EstimateTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    List<EstimateTable> selectByExample(EstimateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    EstimateTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EstimateTable record, @Param("example") EstimateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EstimateTable record, @Param("example") EstimateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EstimateTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EstimateTable record);
}