package com.android.app.dao;

import com.android.app.entity.FriendRelation;
import com.android.app.entity.FriendRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    long countByExample(FriendRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    int deleteByExample(FriendRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    int insert(FriendRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    int insertSelective(FriendRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    List<FriendRelation> selectByExample(FriendRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    FriendRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FriendRelation record, @Param("example") FriendRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FriendRelation record, @Param("example") FriendRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FriendRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FriendRelation record);
}