package com.breakpoint.entity;

import java.util.Date;

public class BbsTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_table.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_table.bbs_id
     *
     * @mbg.generated
     */
    private Long bbsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_table.bbs_title
     *
     * @mbg.generated
     */
    private String bbsTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_table.bbs_desc
     *
     * @mbg.generated
     */
    private String bbsDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_table.bbs_category
     *
     * @mbg.generated
     */
    private String bbsCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_table.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_table.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_table.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_table.bbs_text
     *
     * @mbg.generated
     */
    private String bbsText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_table.id
     *
     * @return the value of bbs_table.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_table.id
     *
     * @param id the value for bbs_table.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_table.bbs_id
     *
     * @return the value of bbs_table.bbs_id
     *
     * @mbg.generated
     */
    public Long getBbsId() {
        return bbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_table.bbs_id
     *
     * @param bbsId the value for bbs_table.bbs_id
     *
     * @mbg.generated
     */
    public void setBbsId(Long bbsId) {
        this.bbsId = bbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_table.bbs_title
     *
     * @return the value of bbs_table.bbs_title
     *
     * @mbg.generated
     */
    public String getBbsTitle() {
        return bbsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_table.bbs_title
     *
     * @param bbsTitle the value for bbs_table.bbs_title
     *
     * @mbg.generated
     */
    public void setBbsTitle(String bbsTitle) {
        this.bbsTitle = bbsTitle == null ? null : bbsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_table.bbs_desc
     *
     * @return the value of bbs_table.bbs_desc
     *
     * @mbg.generated
     */
    public String getBbsDesc() {
        return bbsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_table.bbs_desc
     *
     * @param bbsDesc the value for bbs_table.bbs_desc
     *
     * @mbg.generated
     */
    public void setBbsDesc(String bbsDesc) {
        this.bbsDesc = bbsDesc == null ? null : bbsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_table.bbs_category
     *
     * @return the value of bbs_table.bbs_category
     *
     * @mbg.generated
     */
    public String getBbsCategory() {
        return bbsCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_table.bbs_category
     *
     * @param bbsCategory the value for bbs_table.bbs_category
     *
     * @mbg.generated
     */
    public void setBbsCategory(String bbsCategory) {
        this.bbsCategory = bbsCategory == null ? null : bbsCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_table.user_id
     *
     * @return the value of bbs_table.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_table.user_id
     *
     * @param userId the value for bbs_table.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_table.gmt_create
     *
     * @return the value of bbs_table.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_table.gmt_create
     *
     * @param gmtCreate the value for bbs_table.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_table.gmt_modified
     *
     * @return the value of bbs_table.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_table.gmt_modified
     *
     * @param gmtModified the value for bbs_table.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_table.bbs_text
     *
     * @return the value of bbs_table.bbs_text
     *
     * @mbg.generated
     */
    public String getBbsText() {
        return bbsText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_table.bbs_text
     *
     * @param bbsText the value for bbs_table.bbs_text
     *
     * @mbg.generated
     */
    public void setBbsText(String bbsText) {
        this.bbsText = bbsText == null ? null : bbsText.trim();
    }
}