package com.breakpoint.entity;

import java.io.Serializable;
import java.util.Date;

public class BlogUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_no
     *
     * @mbg.generated
     */
    private Long userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_id_card
     *
     * @mbg.generated
     */
    private String userIdCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_image
     *
     * @mbg.generated
     */
    private String userImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_salt
     *
     * @mbg.generated
     */
    private String userSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_role
     *
     * @mbg.generated
     */
    private Integer userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.id
     *
     * @return the value of blog_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.id
     *
     * @param id the value for blog_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_no
     *
     * @return the value of blog_user.user_no
     *
     * @mbg.generated
     */
    public Long getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_no
     *
     * @param userNo the value for blog_user.user_no
     *
     * @mbg.generated
     */
    public void setUserNo(Long userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_name
     *
     * @return the value of blog_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_name
     *
     * @param userName the value for blog_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.nick_name
     *
     * @return the value of blog_user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.nick_name
     *
     * @param nickName the value for blog_user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_id_card
     *
     * @return the value of blog_user.user_id_card
     *
     * @mbg.generated
     */
    public String getUserIdCard() {
        return userIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_id_card
     *
     * @param userIdCard the value for blog_user.user_id_card
     *
     * @mbg.generated
     */
    public void setUserIdCard(String userIdCard) {
        this.userIdCard = userIdCard == null ? null : userIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_phone
     *
     * @return the value of blog_user.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_phone
     *
     * @param userPhone the value for blog_user.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_image
     *
     * @return the value of blog_user.user_image
     *
     * @mbg.generated
     */
    public String getUserImage() {
        return userImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_image
     *
     * @param userImage the value for blog_user.user_image
     *
     * @mbg.generated
     */
    public void setUserImage(String userImage) {
        this.userImage = userImage == null ? null : userImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_password
     *
     * @return the value of blog_user.user_password
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_password
     *
     * @param userPassword the value for blog_user.user_password
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_salt
     *
     * @return the value of blog_user.user_salt
     *
     * @mbg.generated
     */
    public String getUserSalt() {
        return userSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_salt
     *
     * @param userSalt the value for blog_user.user_salt
     *
     * @mbg.generated
     */
    public void setUserSalt(String userSalt) {
        this.userSalt = userSalt == null ? null : userSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_role
     *
     * @return the value of blog_user.user_role
     *
     * @mbg.generated
     */
    public Integer getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_role
     *
     * @param userRole the value for blog_user.user_role
     *
     * @mbg.generated
     */
    public void setUserRole(Integer userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.gmt_create
     *
     * @return the value of blog_user.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.gmt_create
     *
     * @param gmtCreate the value for blog_user.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.gmt_modified
     *
     * @return the value of blog_user.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.gmt_modified
     *
     * @param gmtModified the value for blog_user.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}