package com.breakpoint.entity;

import java.util.Date;

public class BlogTopic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.topic_id
     *
     * @mbg.generated
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.topic_title
     *
     * @mbg.generated
     */
    private String topicTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.topic_desc
     *
     * @mbg.generated
     */
    private String topicDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.topic_category
     *
     * @mbg.generated
     */
    private String topicCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.photo_path
     *
     * @mbg.generated
     */
    private String photoPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.see_count
     *
     * @mbg.generated
     */
    private Integer seeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_topic.topic_text
     *
     * @mbg.generated
     */
    private String topicText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.id
     *
     * @return the value of blog_topic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.id
     *
     * @param id the value for blog_topic.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.topic_id
     *
     * @return the value of blog_topic.topic_id
     *
     * @mbg.generated
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.topic_id
     *
     * @param topicId the value for blog_topic.topic_id
     *
     * @mbg.generated
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.topic_title
     *
     * @return the value of blog_topic.topic_title
     *
     * @mbg.generated
     */
    public String getTopicTitle() {
        return topicTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.topic_title
     *
     * @param topicTitle the value for blog_topic.topic_title
     *
     * @mbg.generated
     */
    public void setTopicTitle(String topicTitle) {
        this.topicTitle = topicTitle == null ? null : topicTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.topic_desc
     *
     * @return the value of blog_topic.topic_desc
     *
     * @mbg.generated
     */
    public String getTopicDesc() {
        return topicDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.topic_desc
     *
     * @param topicDesc the value for blog_topic.topic_desc
     *
     * @mbg.generated
     */
    public void setTopicDesc(String topicDesc) {
        this.topicDesc = topicDesc == null ? null : topicDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.topic_category
     *
     * @return the value of blog_topic.topic_category
     *
     * @mbg.generated
     */
    public String getTopicCategory() {
        return topicCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.topic_category
     *
     * @param topicCategory the value for blog_topic.topic_category
     *
     * @mbg.generated
     */
    public void setTopicCategory(String topicCategory) {
        this.topicCategory = topicCategory == null ? null : topicCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.type
     *
     * @return the value of blog_topic.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.type
     *
     * @param type the value for blog_topic.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.photo_path
     *
     * @return the value of blog_topic.photo_path
     *
     * @mbg.generated
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.photo_path
     *
     * @param photoPath the value for blog_topic.photo_path
     *
     * @mbg.generated
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath == null ? null : photoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.user_id
     *
     * @return the value of blog_topic.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.user_id
     *
     * @param userId the value for blog_topic.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.gmt_create
     *
     * @return the value of blog_topic.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.gmt_create
     *
     * @param gmtCreate the value for blog_topic.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.gmt_modified
     *
     * @return the value of blog_topic.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.gmt_modified
     *
     * @param gmtModified the value for blog_topic.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.see_count
     *
     * @return the value of blog_topic.see_count
     *
     * @mbg.generated
     */
    public Integer getSeeCount() {
        return seeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.see_count
     *
     * @param seeCount the value for blog_topic.see_count
     *
     * @mbg.generated
     */
    public void setSeeCount(Integer seeCount) {
        this.seeCount = seeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_topic.topic_text
     *
     * @return the value of blog_topic.topic_text
     *
     * @mbg.generated
     */
    public String getTopicText() {
        return topicText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_topic.topic_text
     *
     * @param topicText the value for blog_topic.topic_text
     *
     * @mbg.generated
     */
    public void setTopicText(String topicText) {
        this.topicText = topicText == null ? null : topicText.trim();
    }
}