package com.breakpoint.entity;

import java.util.Date;

public class TbAlbum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.a_id
     *
     * @mbg.generated
     */
    private String aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.a_photo
     *
     * @mbg.generated
     */
    private String aPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.a_msg
     *
     * @mbg.generated
     */
    private String aMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.a_localtion
     *
     * @mbg.generated
     */
    private String aLocaltion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.id
     *
     * @return the value of tb_album.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.id
     *
     * @param id the value for tb_album.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.a_id
     *
     * @return the value of tb_album.a_id
     *
     * @mbg.generated
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.a_id
     *
     * @param aId the value for tb_album.a_id
     *
     * @mbg.generated
     */
    public void setaId(String aId) {
        this.aId = aId == null ? null : aId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.a_photo
     *
     * @return the value of tb_album.a_photo
     *
     * @mbg.generated
     */
    public String getaPhoto() {
        return aPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.a_photo
     *
     * @param aPhoto the value for tb_album.a_photo
     *
     * @mbg.generated
     */
    public void setaPhoto(String aPhoto) {
        this.aPhoto = aPhoto == null ? null : aPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.a_msg
     *
     * @return the value of tb_album.a_msg
     *
     * @mbg.generated
     */
    public String getaMsg() {
        return aMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.a_msg
     *
     * @param aMsg the value for tb_album.a_msg
     *
     * @mbg.generated
     */
    public void setaMsg(String aMsg) {
        this.aMsg = aMsg == null ? null : aMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.a_localtion
     *
     * @return the value of tb_album.a_localtion
     *
     * @mbg.generated
     */
    public String getaLocaltion() {
        return aLocaltion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.a_localtion
     *
     * @param aLocaltion the value for tb_album.a_localtion
     *
     * @mbg.generated
     */
    public void setaLocaltion(String aLocaltion) {
        this.aLocaltion = aLocaltion == null ? null : aLocaltion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.gmt_create
     *
     * @return the value of tb_album.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.gmt_create
     *
     * @param gmtCreate the value for tb_album.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album.gmt_update
     *
     * @return the value of tb_album.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album.gmt_update
     *
     * @param gmtUpdate the value for tb_album.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}