package com.breakpoint.entity;

import java.io.Serializable;
import java.util.Date;

public class Youhuijuan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youhuijuan.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youhuijuan.food_id
     *
     * @mbg.generated
     */
    private String foodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youhuijuan.food_name
     *
     * @mbg.generated
     */
    private String foodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youhuijuan.food_pri_picture
     *
     * @mbg.generated
     */
    private String foodPriPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youhuijuan.food_mon_url
     *
     * @mbg.generated
     */
    private String foodMonUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youhuijuan.food_price
     *
     * @mbg.generated
     */
    private String foodPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youhuijuan.food_youhui
     *
     * @mbg.generated
     */
    private String foodYouhui;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youhuijuan.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column youhuijuan.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youhuijuan.id
     *
     * @return the value of youhuijuan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youhuijuan.id
     *
     * @param id the value for youhuijuan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youhuijuan.food_id
     *
     * @return the value of youhuijuan.food_id
     *
     * @mbg.generated
     */
    public String getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youhuijuan.food_id
     *
     * @param foodId the value for youhuijuan.food_id
     *
     * @mbg.generated
     */
    public void setFoodId(String foodId) {
        this.foodId = foodId == null ? null : foodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youhuijuan.food_name
     *
     * @return the value of youhuijuan.food_name
     *
     * @mbg.generated
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youhuijuan.food_name
     *
     * @param foodName the value for youhuijuan.food_name
     *
     * @mbg.generated
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youhuijuan.food_pri_picture
     *
     * @return the value of youhuijuan.food_pri_picture
     *
     * @mbg.generated
     */
    public String getFoodPriPicture() {
        return foodPriPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youhuijuan.food_pri_picture
     *
     * @param foodPriPicture the value for youhuijuan.food_pri_picture
     *
     * @mbg.generated
     */
    public void setFoodPriPicture(String foodPriPicture) {
        this.foodPriPicture = foodPriPicture == null ? null : foodPriPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youhuijuan.food_mon_url
     *
     * @return the value of youhuijuan.food_mon_url
     *
     * @mbg.generated
     */
    public String getFoodMonUrl() {
        return foodMonUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youhuijuan.food_mon_url
     *
     * @param foodMonUrl the value for youhuijuan.food_mon_url
     *
     * @mbg.generated
     */
    public void setFoodMonUrl(String foodMonUrl) {
        this.foodMonUrl = foodMonUrl == null ? null : foodMonUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youhuijuan.food_price
     *
     * @return the value of youhuijuan.food_price
     *
     * @mbg.generated
     */
    public String getFoodPrice() {
        return foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youhuijuan.food_price
     *
     * @param foodPrice the value for youhuijuan.food_price
     *
     * @mbg.generated
     */
    public void setFoodPrice(String foodPrice) {
        this.foodPrice = foodPrice == null ? null : foodPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youhuijuan.food_youhui
     *
     * @return the value of youhuijuan.food_youhui
     *
     * @mbg.generated
     */
    public String getFoodYouhui() {
        return foodYouhui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youhuijuan.food_youhui
     *
     * @param foodYouhui the value for youhuijuan.food_youhui
     *
     * @mbg.generated
     */
    public void setFoodYouhui(String foodYouhui) {
        this.foodYouhui = foodYouhui == null ? null : foodYouhui.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youhuijuan.gmt_create
     *
     * @return the value of youhuijuan.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youhuijuan.gmt_create
     *
     * @param gmtCreate the value for youhuijuan.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column youhuijuan.gmt_update
     *
     * @return the value of youhuijuan.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column youhuijuan.gmt_update
     *
     * @param gmtUpdate the value for youhuijuan.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}